;/*FB_PKG_DELIM*/

__d("CometComposerLinksPluginForLexicalDeferred.react",["createComposerDeferredPlugin","react","requireDeferred"],(function(a,b,c,d,e,f,g){"use strict";var h;h||d("react");a=c("createComposerDeferredPlugin")(c("requireDeferred")("CometComposerLinksPluginForLexicalWithDefaultExport.react").__setRef("CometComposerLinksPluginForLexicalDeferred.react"));g["default"]=a}),98);
__d("CometComposerPostSettingFeatureTypes",["$InternalEnum"],(function(a,b,c,d,e,f){"use strict";a=b("$InternalEnum").Mirrored(["CREATOR_COMPOSER","ADMIN_CROSS_POST","POST_COLLABORATOR"]);f.CometComposerPostSettingFeatureTypes=a}),66);
__d("CometEventPermalinkTab",["$InternalEnum"],(function(a,b,c,d,e,f){a=b("$InternalEnum")({ABOUT:"about",DISCUSSION:"discussion",BRACKETS:"brackets",BROADCASTS:"broadcasts",PARTICIPANTS:"participants",STANDINGS:"standings",VIDEOS:"videos",PAID_ACCESS:"paid_access"});c=a;f["default"]=c}),66);
__d("EventCometActionContextDefault",[],(function(a,b,c,d,e,f){"use strict";a={event_action_history:[]};f["default"]=a}),66);
__d("EventCometActionContext",["EventCometActionContextDefault","react"],(function(a,b,c,d,e,f,g){"use strict";var h;a=h||d("react");b=a.createContext(c("EventCometActionContextDefault"));g["default"]=b}),98);
__d("EventCometActionLoggerUtils",["CometRouteURL"],(function(a,b,c,d,e,f,g){"use strict";var h={mechanism:"unknown",surface:"unknown"},i=3;function a(a,b){var c=[].concat(a.event_action_history||[]);c.length>=i&&(c=c.slice(c.length-i+1));var d=j(a);c.push({event_tracking:d.event_tracking,extra_data:d.extra_data,mechanism:b.mechanism,surface:b.surface});return babelHelpers["extends"]({},a,{event_action_history:c})}function j(a){a=a.event_action_history;if(a==null||a[a.length-1]==null)return h;return a.length>=2?a[a.length-2]:a[a.length-1]}function b(){var a=d("CometRouteURL").useRouteURL(),b=/\/events\/\d+/;if(b.test(a))return"permalink";if(a.includes("/events/calendar"))return"bookmark_calendar";if(a.includes("/events"))return"bookmark";return a.includes("profile.php")?"timeline":"newsfeed"}g.createForNewSurface=a;g.getLastActionHistoryEntry=j;g.useExtractEventComposerSurface=b}),98);
__d("FBPayUPLSessionIDGenerator",["uuidv4"],(function(a,b,c,d,e,f,g){"use strict";var h="upl";function a(){var a=[h,Date.now(),c("uuidv4")()];return a.join("_")}g.sessionIDGenerator=a}),98);
__d("GSUALoggingUtils",[],(function(a,b,c,d,e,f,g){"use strict";function a(a,b,c,d,e,f){if(b===!0)return"group_mall_featured_card";switch(a){case"homepage_stream":return"newsfeed";case"group":if(d==="GROUP_ANNOUNCEMENTS_FEED")return"group_mall_featured_tab";return f!==null?f==="DISCUSSION"?"group_mall_discussion":"group_mall_bsg_tab":(b=e)!=null?b:"group_mall_bsg_tab";case"groups_tab":return"groups_tab";case"group_serp":return"group_search";case"search_results_page":if(c==="group_posts"||c==="groups_home")return"group_tab_serp";return c==="top"||c==="posts"?"global_search_module_result":"group_mall_topics_feed";case"group_permalink":return"group_permalink";default:return"unknown"}}g.storyRenderLocationToSurface=a}),98);
__d("XCometEventPermalinkControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsRouteBuilder")("/events/{event_id}/{?child_event_id}/",Object.freeze({active_tab:"about",show_created_event_toast:!1,hide_invite_flow_filter_groups:!1,show_join_in_vr_dialog:!1}),void 0);b=a;g["default"]=b}),98);
__d("castToEnum",[],(function(a,b,c,d,e,f){"use strict";function a(a,b,c){var d=Object.keys(b);for(var e=0;e<d.length;e++)if(b[d[e]]===a)return b[d[e]];return c}f["default"]=a}),66);
__d("cometFormattedTextIneligibilityCheck",[],(function(a,b,c,d,e,f){"use strict";function a(a,b,c){var d;b===void 0&&(b=130);c===void 0&&(c=3);return((d=(d=a.match(/\n/g))==null?void 0:d.length)!=null?d:0)>=c||a.length>b}f["default"]=a}),66);
__d("useBaseDynamicEntryPointDialog",["CometDialogContext","CometRelay","CometSuspendedDialogImpl.react","clearTimeout","react","react-compiler-runtime","setTimeout","tracePolicyFromResource","useCometRelayEntrypointContextualEnvironmentProvider"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||(h=d("react"));b=h;b.useCallback;var j=b.useContext,k=b.useEffect,l=b.useRef;function m(a){var b=d("react-compiler-runtime").c(17),e=a.entryPoint,f=a.environmentProvider,g=a.onClose,h=a.otherProps,j=a.overrideRelayEnv,m=a.preloadedEntryPoint,n=a.preloadParams;a=d("CometRelay").useEntryPointLoader(f,e);var o=a[0],p=a[1],q=a[2],r=(f=o)!=null?f:m,s=l(null);b[0]!==q||b[1]!==r.isDisposed||b[2]!==n||b[3]!==m||b[4]!==p||b[5]!==o?(e=function(){s.current!=null&&(c("clearTimeout")(s.current),s.current=null);r.isDisposed&&p(n);return function(){s.current=c("setTimeout")(function(){o?q():m.dispose(),s.current=null},6e4)}},a=[q,r.isDisposed,m,n,p,o],b[0]=q,b[1]=r.isDisposed,b[2]=n,b[3]=m,b[4]=p,b[5]=o,b[6]=e,b[7]=a):(e=b[6],a=b[7]);k(e,a);b[8]!==g||b[9]!==h?(f=babelHelpers["extends"]({},h,{onClose:g}),b[8]=g,b[9]=h,b[10]=f):f=b[10];e=f;b[11]!==m||b[12]!==e?(a=i.jsx(d("CometRelay").EntryPointContainer,{entryPointReference:m,props:e}),b[11]=m,b[12]=e,b[13]=a):a=b[13];g=a;b[14]!==g||b[15]!==j?(h=j!=null?i.jsx(d("CometRelay").RelayEnvironmentProvider,{environment:j,children:g}):g,b[14]=g,b[15]=j,b[16]=h):h=b[16];return h}function a(a,b,e,f){var g=d("react-compiler-runtime").c(7),h=c("useCometRelayEntrypointContextualEnvironmentProvider")(f),i=j(c("CometDialogContext")),k;g[0]!==i||g[1]!==a||g[2]!==h||g[3]!==e||g[4]!==f||g[5]!==b?(k=function(g,j,k,l){var n=d("CometRelay").loadEntryPoint(h,a,g),o=function(){for(var a=arguments.length,b=new Array(a),c=0;c<a;c++)b[c]=arguments[c];var d=b;k&&k.apply(void 0,d);var e=n==null?void 0:n.dispose;e&&e()};i(c("CometSuspendedDialogImpl.react"),{dialog:m,dialogProps:{entryPoint:a,environmentProvider:h,otherProps:j,overrideRelayEnv:f,preloadedEntryPoint:n,preloadParams:g},fallback:e},{loadType:"entrypoint",preloadTrigger:b,tracePolicy:(j=l)!=null?j:c("tracePolicyFromResource")("comet.dialog",a.root)},o)},g[0]=i,g[1]=a,g[2]=h,g[3]=e,g[4]=f,g[5]=b,g[6]=k):k=g[6];return k}g["default"]=a}),98);
__d("useCometDynamicEntryPointDialog",["FDSDialogLoadingState.react","react","useBaseDynamicEntryPointDialog"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||d("react"),j=function(a){return i.jsx(c("FDSDialogLoadingState.react"),{onClose:a})};function a(a,b,d,e){return c("useBaseDynamicEntryPointDialog")(a,b,(a=d)!=null?a:j,e)}g["default"]=a}),98);